import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  preflight: true,
  include: ["./src/**/*.{ts,tsx,js,jsx}"],
  exclude: ["./styled-system/**/*"],
  outdir: "styled-system",
  importMap: "styled-system",
  theme: {
    extend: {
      tokens: {
        colors: {
          background: { value: "#0D1117" },
          backgroundSoft: { value: "#11161D" },
          surface: { value: "#171C23" },
          surfaceElevated: { value: "#202631" },
          surfacePressed: { value: "#2A313D" },
          border: { value: "#323A46" },
          borderMuted: { value: "#242B35" },
          text: { value: "#F5F7FA" },
          textMuted: { value: "#A7AFBD" },
          textSubtle: { value: "#6F7785" },
          primary: { value: "#A7F01B" },
          primaryHover: { value: "#B8FF2C" },
          primaryPressed: { value: "#89CC16" },
          primarySoft: { value: "#24340D" },
          blue: { value: "#4F8CFF" },
          blueSoft: { value: "#17233D" },
          orange: { value: "#FF7A2F" },
          orangeSoft: { value: "#351C10" },
          danger: { value: "#FF5C5C" },
          dangerSoft: { value: "#351616" },
          success: { value: "#8FEA4B" },
          warning: { value: "#FFCC66" },
        },
      },
      semanticTokens: {
        colors: {
          bg: { value: "{colors.background}" },
          bgSoft: { value: "{colors.backgroundSoft}" },
          card: { value: "{colors.surface}" },
          cardElevated: { value: "{colors.surfaceElevated}" },
          fg: { value: "{colors.text}" },
          fgMuted: { value: "{colors.textMuted}" },
          fgSubtle: { value: "{colors.textSubtle}" },
          accent: { value: "{colors.primary}" },
          accentHover: { value: "{colors.primaryHover}" },
          accentPressed: { value: "{colors.primaryPressed}" },
          accentSoft: { value: "{colors.primarySoft}" },
          line: { value: "{colors.border}" },
          lineMuted: { value: "{colors.borderMuted}" },
        },
      },
    },
  },
  globalCss: {
    ":root": {
      color: "fg",
      backgroundColor: "bg",
      colorScheme: "dark",
      fontFamily: 'system-ui, "Segoe UI", Roboto, sans-serif',
      fontSynthesis: "none",
      textRendering: "optimizeLegibility",
      WebkitFontSmoothing: "antialiased",
      MozOsxFontSmoothing: "grayscale",
    },
    body: {
      marginBlock: "0",
      marginInline: "0",
    },
  },
});
