import { css, cva } from "styled-system/css";

export const styles = {
  root: css({
    boxSizing: "border-box",
    inlineSize: "100%",
    maxInlineSize: "960px",
    marginInline: "auto",
    paddingInline: { base: "16px", sm: "24px" },
    paddingBlockStart: { base: "14px", sm: "32px" },
    paddingBlockEnd: { base: "20px", sm: "32px" },
    color: "fg",
  }),
  header: css({
    display: "grid",
    gap: { base: "14px", sm: "18px" },
    alignItems: "end",
    gridTemplateColumns: {
      base: "1fr",
      md: "minmax(0, 1fr) auto",
    },
  }),
  headerText: css({
    display: "grid",
    gap: "8px",
  }),
  eyebrow: css({
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "0",
    textTransform: "uppercase",
  }),
  title: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "28px", sm: "44px" },
    fontWeight: "800",
    lineHeight: "1",
    textWrap: "balance",
  }),
  description: css({
    maxInlineSize: "580px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: { base: "15px", sm: "16px" },
    lineHeight: "1.5",
  }),
  headerActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(0, 1.1fr)",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
  }),
  countBadge: css({
    inlineSize: { base: "100%", sm: "auto" },
    minBlockSize: "48px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    paddingBlock: "10px",
    paddingInline: "14px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  countValue: css({
    color: "accent",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  countLabel: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1",
  }),
  button: cva({
    base: {
      minBlockSize: "44px",
      inlineSize: { base: "100%", sm: "auto" },
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      paddingBlock: "10px",
      paddingInline: "14px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "800",
      lineHeight: "1",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      _disabled: {
        cursor: "not-allowed",
        opacity: "0.55",
      },
    },
    variants: {
      variant: {
        danger: {
          backgroundColor: "orangeSoft",
          borderColor: "orange",
          color: "warning",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
        primary: {
          backgroundColor: "accent",
          borderColor: "accent",
          color: "bg",
          _hover: {
            backgroundColor: "accentHover",
            borderColor: "accentHover",
          },
          _active: {
            backgroundColor: "accentPressed",
            borderColor: "accentPressed",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fg",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  icon: css({
    inlineSize: "18px",
    blockSize: "18px",
    flexShrink: "0",
  }),
  iconButton: cva({
    base: {
      inlineSize: "40px",
      blockSize: "40px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      _disabled: {
        cursor: "not-allowed",
        opacity: "0.55",
      },
    },
    variants: {
      variant: {
        ghost: {
          backgroundColor: "transparent",
          borderColor: "lineMuted",
          color: "fgMuted",
          _hover: {
            backgroundColor: "cardElevated",
            color: "fg",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fgMuted",
          _hover: {
            color: "fg",
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  feedback: css({
    marginBlockStart: "18px",
    marginBlockEnd: "0",
    marginInline: "0",
    paddingBlock: "12px",
    paddingInline: "14px",
    color: "warning",
    backgroundColor: "orangeSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "orange",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "14px",
    fontWeight: "700",
  }),
  emptyState: css({
    display: "grid",
    justifyItems: "start",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
    paddingBlock: { base: "20px", sm: "24px" },
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  emptyIcon: css({
    inlineSize: "32px",
    blockSize: "32px",
    color: "accent",
  }),
  emptyTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "22px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  emptyDescription: css({
    maxInlineSize: "520px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "15px",
    lineHeight: "1.45",
  }),
  emptyActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "1fr",
    flexWrap: "wrap",
    gap: "10px",
    inlineSize: "100%",
  }),
  startPanel: css({
    display: "grid",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
  }),
  startPanelHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  }),
  sectionTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "18px",
    fontWeight: "800",
    lineHeight: "1.15",
  }),
  textButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minBlockSize: "36px",
    paddingBlock: "6px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "accent",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  planList: css({
    display: "grid",
    gap: "10px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  planCard: css({
    display: "grid",
    gap: "12px",
    gridTemplateColumns: {
      base: "minmax(0, 1fr)",
      sm: "minmax(0, 1fr) auto",
    },
    alignItems: "center",
    paddingBlock: "14px",
    paddingInline: "14px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  planSummary: css({
    minInlineSize: "0",
    display: "grid",
    gap: "4px",
  }),
  planName: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "18px",
    fontWeight: "800",
    lineHeight: "1.15",
  }),
  planMeta: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgSubtle",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.2",
  }),
  planPreview: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    fontWeight: "700",
    lineHeight: "1.3",
  }),
  sessionPanel: css({
    display: "grid",
    gap: "16px",
    marginBlockStart: { base: "18px", sm: "24px" },
    paddingBlock: { base: "16px", sm: "18px" },
    paddingInline: "16px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  sessionHeader: css({
    display: "grid",
    gap: "12px",
    gridTemplateColumns: {
      base: "1fr",
      sm: "minmax(0, 1fr) auto",
    },
    alignItems: "start",
  }),
  sessionHeading: css({
    display: "grid",
    gap: "4px",
  }),
  sessionStatus: css({
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "12px",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    textTransform: "uppercase",
  }),
  sessionTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "24px", sm: "30px" },
    fontWeight: "800",
    lineHeight: "1.05",
  }),
  sessionMeta: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    fontWeight: "700",
    lineHeight: "1.35",
  }),
  sessionActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "1fr",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
    justifyContent: {
      base: "stretch",
      sm: "end",
    },
  }),
  restTimerDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "420px",
    display: "grid",
    justifyItems: "center",
    gap: "18px",
    paddingBlock: { base: "28px", sm: "34px" },
    paddingInline: { base: "18px", sm: "24px" },
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  restTimerText: css({
    display: "grid",
    justifyItems: "center",
    gap: "8px",
    textAlign: "center",
  }),
  restTimerLabel: css({
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "12px",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    textTransform: "uppercase",
  }),
  restTimerValue: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "64px", sm: "76px" },
    fontWeight: "900",
    lineHeight: "0.95",
    fontVariantNumeric: "tabular-nums",
  }),
  restTimerMeta: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.3",
  }),
  exerciseList: css({
    display: "grid",
    gap: "10px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  exerciseCard: css({
    display: "grid",
    gap: "12px",
    paddingBlock: "12px",
    paddingInline: "12px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  exerciseToggle: css({
    inlineSize: "100%",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "12px",
    alignItems: "center",
    paddingBlock: "0",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "fg",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    textAlign: "start",
  }),
  exerciseHeading: css({
    display: "grid",
    gap: "4px",
  }),
  exerciseName: css({
    color: "fg",
    fontSize: "16px",
    fontWeight: "800",
    lineHeight: "1.2",
  }),
  exerciseMeta: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.3",
  }),
  exerciseChevron: cva({
    base: {
      inlineSize: "20px",
      blockSize: "20px",
      color: "fgMuted",
      transition: "transform 120ms ease",
    },
    variants: {
      open: {
        true: {
          transform: "rotate(180deg)",
        },
        false: {
          transform: "rotate(0deg)",
        },
      },
    },
    defaultVariants: {
      open: false,
    },
  }),
  exerciseDetails: css({
    display: "grid",
    gap: "12px",
  }),
  setList: css({
    display: "grid",
    gap: "6px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  setRow: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "center",
    paddingBlock: "8px",
    paddingInline: "10px",
    backgroundColor: "bgSoft",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.35",
  }),
  setSummary: css({
    minInlineSize: "0",
  }),
  setActionButton: css({
    inlineSize: "30px",
    blockSize: "30px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: "0",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    _hover: {
      backgroundColor: "cardElevated",
      borderColor: "lineMuted",
      color: "fg",
    },
    _focusVisible: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
      outline: "none",
    },
  }),
  setActionIcon: css({
    inlineSize: "16px",
    blockSize: "16px",
    flexShrink: "0",
  }),
  setForm: css({
    display: "grid",
    gap: "10px",
  }),
  setFields: css({
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
  }),
  setField: css({
    minInlineSize: "0",
    display: "grid",
    gap: "6px",
  }),
  setLabel: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  setInput: css({
    inlineSize: "100%",
    minBlockSize: "44px",
    boxSizing: "border-box",
    paddingBlock: "10px",
    paddingInline: "10px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    fontWeight: "700",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  setEditForm: css({
    display: "grid",
    gap: "14px",
  }),
  formHeader: css({
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
  }),
  formHeading: css({
    display: "grid",
    gap: "5px",
  }),
  formTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  formDescription: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.4",
  }),
  formActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "1fr",
    flexWrap: "wrap",
    gap: "10px",
  }),
  dialogOverlay: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "30",
    backgroundColor: "rgba(13, 17, 23, 0.78)",
    backdropFilter: "blur(8px)",
  }),
  dialogViewport: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "31",
    display: "grid",
    placeItems: "center",
    paddingBlock: "16px",
    paddingInline: "16px",
    pointerEvents: "none",
  }),
  setDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "520px",
    maxBlockSize: "calc(100vb - 32px)",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  exerciseDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "520px",
    maxBlockSize: "calc(100vb - 32px)",
    overflowBlock: "auto",
    display: "grid",
    gap: "14px",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  exercisePickerList: css({
    display: "grid",
    gap: "10px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  exercisePickerItem: css({
    display: "grid",
    gap: "10px",
    gridTemplateColumns: {
      base: "minmax(0, 1fr)",
      sm: "minmax(0, 1fr) auto",
    },
    alignItems: "center",
    paddingBlock: "12px",
    paddingInline: "12px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  visuallyHidden: css({
    srOnly: true,
  }),
};
