import { css, cva } from "styled-system/css";

export const styles = {
  root: css({
    boxSizing: "border-box",
    inlineSize: "100%",
    maxInlineSize: "640px",
    marginInline: "auto",
    paddingInline: { base: "16px", sm: "24px" },
    paddingBlockStart: { base: "14px", sm: "28px" },
    paddingBlockEnd: { base: "20px", sm: "32px" },
    color: "fg",
  }),
  dashboardHeader: css({
    minBlockSize: "48px",
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
    paddingInlineEnd: "56px",
  }),
  dashboardGreeting: css({
    minInlineSize: "0",
    display: "grid",
    gap: "5px",
  }),
  dashboardTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "26px", sm: "34px" },
    fontWeight: "900",
    lineHeight: "1.08",
  }),
  dashboardSubtitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    fontWeight: "650",
    lineHeight: "1.35",
  }),
  dashboard: css({
    display: "grid",
    gap: "18px",
    marginBlockStart: "20px",
  }),
  dashboardSection: css({
    display: "grid",
    gap: "10px",
  }),
  sectionHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  }),
  button: cva({
    base: {
      minBlockSize: "44px",
      inlineSize: { base: "100%", sm: "auto" },
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      paddingBlock: "10px",
      paddingInline: "14px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "800",
      lineHeight: "1",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      _disabled: {
        cursor: "not-allowed",
        opacity: "0.55",
      },
    },
    variants: {
      variant: {
        danger: {
          backgroundColor: "orangeSoft",
          borderColor: "orange",
          color: "warning",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
        primary: {
          backgroundColor: "accent",
          borderColor: "accent",
          color: "bg",
          _hover: {
            backgroundColor: "accentHover",
            borderColor: "accentHover",
          },
          _active: {
            backgroundColor: "accentPressed",
            borderColor: "accentPressed",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fg",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  icon: css({
    inlineSize: "18px",
    blockSize: "18px",
    flexShrink: "0",
  }),
  iconButton: cva({
    base: {
      inlineSize: "40px",
      blockSize: "40px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      _disabled: {
        cursor: "not-allowed",
        opacity: "0.55",
      },
    },
    variants: {
      variant: {
        ghost: {
          backgroundColor: "transparent",
          borderColor: "lineMuted",
          color: "fgMuted",
          _hover: {
            backgroundColor: "cardElevated",
            color: "fg",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fgMuted",
          _hover: {
            color: "fg",
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  feedback: css({
    marginBlockStart: "18px",
    marginBlockEnd: "0",
    marginInline: "0",
    paddingBlock: "12px",
    paddingInline: "14px",
    color: "warning",
    backgroundColor: "orangeSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "orange",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "14px",
    fontWeight: "700",
  }),
  emptyState: css({
    display: "grid",
    justifyItems: "start",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
    paddingBlock: { base: "20px", sm: "24px" },
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  emptyIcon: css({
    inlineSize: "32px",
    blockSize: "32px",
    color: "accent",
  }),
  emptyTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "22px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  emptyDescription: css({
    maxInlineSize: "520px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "15px",
    lineHeight: "1.45",
  }),
  sectionTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "16px",
    fontWeight: "900",
    lineHeight: "1.15",
  }),
  textButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minBlockSize: "36px",
    paddingBlock: "6px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "accent",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  todayWorkoutCard: css({
    position: "relative",
    inlineSize: "100%",
    minBlockSize: "118px",
    display: "grid",
    gridTemplateColumns: "44px minmax(0, 1fr) auto",
    gridTemplateRows: "auto auto",
    columnGap: "14px",
    rowGap: "12px",
    alignItems: "center",
    paddingBlock: "16px",
    paddingInline: "16px",
    backgroundColor: "card",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.03)",
    textAlign: "start",
  }),
  todayWorkoutIcon: css({
    inlineSize: "44px",
    blockSize: "44px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "accent",
    color: "bg",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
  }),
  todayWorkoutIconSvg: css({
    inlineSize: "24px",
    blockSize: "24px",
  }),
  todayWorkoutText: css({
    minInlineSize: "0",
    display: "grid",
    gap: "5px",
  }),
  todayWorkoutName: css({
    overflow: "hidden",
    color: "fg",
    fontSize: "18px",
    fontWeight: "900",
    lineHeight: "1.15",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  todayWorkoutMeta: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "700",
    lineHeight: "1.3",
  }),
  todayWorkoutChevron: css({
    inlineSize: "20px",
    blockSize: "20px",
    color: "fgMuted",
  }),
  progressTrack: css({
    gridColumn: "1 / -1",
    overflow: "hidden",
    inlineSize: "100%",
    blockSize: "5px",
    backgroundColor: "line",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
  }),
  progressFill: css({
    display: "block",
    blockSize: "100%",
    backgroundColor: "accent",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
  }),
  primaryStartButton: css({
    gridColumn: "1 / -1",
    minBlockSize: "54px",
    inlineSize: "100%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    paddingBlock: "13px",
    paddingInline: "18px",
    backgroundColor: "accent",
    color: "bg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accent",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "900",
    lineHeight: "1",
    _hover: {
      backgroundColor: "accentHover",
      borderColor: "accentHover",
    },
    _active: {
      backgroundColor: "accentPressed",
      borderColor: "accentPressed",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.55",
    },
  }),
  statGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
  }),
  statCard: css({
    minBlockSize: "96px",
    display: "grid",
    placeItems: "center",
    alignContent: "center",
    gap: "6px",
    paddingBlock: "13px",
    paddingInline: "8px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  statIcon: cva({
    base: {
      inlineSize: "20px",
      blockSize: "20px",
    },
    variants: {
      tone: {
        accent: { color: "accent" },
        blue: { color: "blue" },
        orange: { color: "orange" },
      },
    },
  }),
  statValue: css({
    color: "fg",
    fontSize: "20px",
    fontWeight: "900",
    lineHeight: "1",
    fontVariantNumeric: "tabular-nums",
  }),
  statLabel: css({
    color: "fgMuted",
    fontSize: "10px",
    fontWeight: "750",
    lineHeight: "1.2",
    textAlign: "center",
  }),
  progressHighlightList: css({
    display: "grid",
    gap: "8px",
  }),
  progressHighlight: css({
    minBlockSize: "58px",
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr)",
    gap: "10px",
    alignItems: "center",
    paddingBlock: "12px",
    paddingInline: "13px",
    backgroundColor: "card",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "13px",
    fontWeight: "750",
    lineHeight: "1.35",
  }),
  progressHighlightIcon: css({
    inlineSize: "20px",
    blockSize: "20px",
    color: "accent",
    justifySelf: "center",
  }),
  dashboardEmpty: css({
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "14px",
    paddingInline: "14px",
    backgroundColor: "card",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "13px",
    lineHeight: "1.4",
  }),
  recoveryIcon: css({
    inlineSize: "19px",
    blockSize: "19px",
    color: "accent",
  }),
  recoveryList: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", sm: "1fr 1fr" },
    gap: "8px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  recoveryItem: css({
    minInlineSize: "0",
    minBlockSize: "60px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "10px",
    alignItems: "center",
    paddingBlock: "10px",
    paddingInline: "12px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  recoveryText: css({
    minInlineSize: "0",
    display: "grid",
    gap: "3px",
    "& strong": {
      overflow: "hidden",
      color: "fg",
      fontSize: "13px",
      lineHeight: "1.15",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& span": {
      color: "fgMuted",
      fontSize: "10px",
      fontWeight: "700",
      lineHeight: "1.2",
    },
  }),
  recoveryBadge: cva({
    base: {
      display: "inline-flex",
      paddingBlock: "5px",
      paddingInline: "8px",
      borderStartStartRadius: "999px",
      borderStartEndRadius: "999px",
      borderEndStartRadius: "999px",
      borderEndEndRadius: "999px",
      fontSize: "10px",
      fontWeight: "850",
      lineHeight: "1",
    },
    variants: {
      state: {
        ready: { backgroundColor: "accentSoft", color: "accent" },
        recent: { backgroundColor: "cardElevated", color: "blue" },
        rest: { backgroundColor: "orangeSoft", color: "warning" },
      },
    },
  }),
  sessionPanel: css({
    display: "grid",
    gap: "16px",
    marginBlockStart: { base: "18px", sm: "24px" },
    paddingBlock: { base: "16px", sm: "18px" },
    paddingInline: "16px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  overviewSection: css({
    display: "grid",
    gap: "10px",
  }),
  overviewHint: css({
    marginBlockStart: "4px",
    marginBlockEnd: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "12px",
    lineHeight: "1.35",
  }),
  overviewExerciseList: css({
    display: "grid",
    gap: "8px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  overviewExerciseButton: css({
    inlineSize: "100%",
    minBlockSize: "76px",
    display: "grid",
    gridTemplateColumns: "36px minmax(0, 1fr) auto 18px",
    gap: "10px",
    alignItems: "center",
    paddingBlock: "11px",
    paddingInline: "11px",
    backgroundColor: "cardElevated",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    textAlign: "start",
    transition: "background-color 120ms ease, border-color 120ms ease",
    _hover: {
      backgroundColor: "surfacePressed",
      borderColor: "line",
    },
    _focusVisible: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
      outline: "none",
    },
  }),
  overviewExerciseNumber: css({
    inlineSize: "34px",
    blockSize: "34px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "bgSoft",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    fontSize: "12px",
    fontWeight: "900",
  }),
  overviewExerciseText: css({
    minInlineSize: "0",
    display: "grid",
    gap: "3px",
    "& strong": {
      overflow: "hidden",
      fontSize: "15px",
      fontWeight: "850",
      lineHeight: "1.15",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& span": {
      color: "fgMuted",
      fontSize: "12px",
      fontWeight: "700",
      lineHeight: "1.2",
    },
    "& small": {
      overflow: "hidden",
      color: "fgSubtle",
      fontSize: "11px",
      fontWeight: "650",
      lineHeight: "1.2",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  }),
  overviewExerciseState: cva({
    base: {
      display: { base: "none", sm: "inline-flex" },
      paddingBlock: "5px",
      paddingInline: "8px",
      borderStartStartRadius: "999px",
      borderStartEndRadius: "999px",
      borderEndStartRadius: "999px",
      borderEndEndRadius: "999px",
      fontSize: "10px",
      fontWeight: "850",
      lineHeight: "1",
      whiteSpace: "nowrap",
    },
    variants: {
      complete: {
        true: { backgroundColor: "accentSoft", color: "accent" },
        false: { backgroundColor: "bgSoft", color: "fgMuted" },
      },
    },
    defaultVariants: { complete: false },
  }),
  overviewChevron: css({
    inlineSize: "18px",
    blockSize: "18px",
    color: "fgMuted",
  }),
  overviewActions: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", sm: "repeat(2, minmax(0, 1fr))" },
    gap: "8px",
  }),
  overviewEmpty: css({
    display: "grid",
    justifyItems: "start",
    gap: "10px",
    paddingBlock: "18px",
    paddingInline: "16px",
    backgroundColor: "bgSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  focusedPanel: css({
    minBlockSize: "calc(100svh - 28px)",
    display: "grid",
    alignContent: "start",
    gap: "14px",
    paddingBlockEnd: "88px",
  }),
  focusedTopBar: css({
    position: "sticky",
    zIndex: "10",
    insetBlockStart: "0",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
    gap: "8px",
    alignItems: "center",
    minBlockSize: "54px",
    paddingBlock: "7px",
    backgroundColor: "rgba(13, 17, 23, 0.94)",
    borderBlockEndWidth: "1px",
    borderInlineWidth: "0",
    borderStyle: "solid",
    borderColor: "lineMuted",
    backdropFilter: "blur(14px)",
  }),
  focusedBackButton: css({
    minBlockSize: "40px",
    display: "inline-flex",
    alignItems: "center",
    justifySelf: "start",
    gap: "5px",
    paddingBlock: "7px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "fg",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "800",
  }),
  focusedPosition: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
    fontVariantNumeric: "tabular-nums",
  }),
  focusedFinishButton: css({
    minBlockSize: "40px",
    justifySelf: "end",
    paddingBlock: "7px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "accent",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "850",
    _disabled: { cursor: "not-allowed", opacity: "0.55" },
  }),
  focusedHero: css({
    display: "grid",
    gap: "6px",
    paddingBlockStart: "5px",
    paddingBlockEnd: "2px",
    "& > h1": {
      marginBlock: "0",
      marginInline: "0",
      color: "fg",
      fontSize: { base: "30px", sm: "38px" },
      fontWeight: "900",
      lineHeight: "1.02",
      textWrap: "balance",
    },
  }),
  focusedHeroMeta: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    "& > p": {
      marginBlock: "0",
      marginInline: "0",
      color: "fgMuted",
      fontSize: "11px",
      fontWeight: "850",
      letterSpacing: "0.05em",
      lineHeight: "1",
      textTransform: "uppercase",
    },
  }),
  focusedSaveStatus: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    color: "fgSubtle",
    fontSize: "10px",
    fontWeight: "750",
    "& svg": { inlineSize: "13px", blockSize: "13px" },
  }),
  referenceGrid: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    overflow: "hidden",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "9px",
    borderStartEndRadius: "9px",
    borderEndStartRadius: "9px",
    borderEndEndRadius: "9px",
  }),
  referenceCard: css({
    minInlineSize: "0",
    minBlockSize: "68px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "7px",
    alignItems: "center",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "0",
    borderInlineStartWidth: "0",
    borderInlineEndWidth: "0",
    borderStyle: "solid",
    borderColor: "lineMuted",
    textAlign: "start",
    "& > span": { minInlineSize: "0", display: "grid", gap: "3px" },
    "& small": {
      color: "fgSubtle",
      fontSize: "9px",
      fontWeight: "850",
      letterSpacing: "0.04em",
      textTransform: "uppercase",
    },
    "& strong": {
      overflow: "hidden",
      color: "fg",
      fontSize: "14px",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "&[type=button]": { cursor: "pointer" },
    _hover: { backgroundColor: "cardElevated" },
  }),
  referenceCopyAction: css({
    display: "inline-flex!",
    gridAutoFlow: "column",
    alignItems: "center",
    gap: "4px!",
    color: "fgMuted",
    fontSize: "10px",
    fontWeight: "850",
    "& svg": { inlineSize: "14px", blockSize: "14px" },
  }),
  focusedSetForm: css({
    display: "grid",
    gap: "12px",
    paddingBlockStart: "10px",
  }),
  focusedSetHeading: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "800",
    paddingInline: "1px",
    textTransform: "uppercase",
    "& strong": { color: "accent", fontSize: "13px", fontVariantNumeric: "tabular-nums" },
  }),
  focusedSetFields: css({
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: "10px",
  }),
  focusedSetField: css({
    position: "relative",
    minBlockSize: "108px",
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: "4px",
    paddingBlock: "12px",
    paddingInline: "10px",
    backgroundColor: "bgSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "10px",
    borderStartEndRadius: "10px",
    borderEndStartRadius: "10px",
    borderEndEndRadius: "10px",
    "& > span": {
      color: "fgMuted",
      fontSize: "11px",
      fontWeight: "850",
      letterSpacing: "0.04em",
      textTransform: "uppercase",
    },
    "& > input": {
      inlineSize: "100%",
      minInlineSize: "0",
      paddingBlock: "0",
      paddingInline: "4px",
      backgroundColor: "transparent",
      color: "fg",
      borderBlockWidth: "0",
      borderInlineWidth: "0",
      fontSize: { base: "34px", sm: "40px" },
      fontWeight: "900",
      lineHeight: "1",
      outline: "none",
      textAlign: "center",
      fontVariantNumeric: "tabular-nums",
      _placeholder: { color: "fgSubtle", opacity: "0.55" },
    },
    "& > small": { color: "fgSubtle", fontSize: "11px", fontWeight: "750" },
    _focusWithin: { borderColor: "accent", boxShadow: "0 0 0 3px token(colors.accentSoft)" },
  }),
  focusedRestField: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "750",
  }),
  focusedRestInput: css({
    minBlockSize: "40px",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    paddingBlock: "6px",
    paddingInline: "9px",
    backgroundColor: "bgSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    "& svg": { inlineSize: "15px", blockSize: "15px", color: "accent" },
    "& input": {
      inlineSize: "54px",
      paddingBlock: "0",
      paddingInline: "0",
      backgroundColor: "transparent",
      color: "fg",
      borderBlockWidth: "0",
      borderInlineWidth: "0",
      fontSize: "16px",
      fontWeight: "850",
      outline: "none",
      textAlign: "end",
    },
    "& small": { color: "fgSubtle", fontSize: "10px", fontWeight: "750" },
    _focusWithin: { borderColor: "accent" },
  }),
  completeSetButton: css({
    inlineSize: "100%",
    minBlockSize: "56px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "9px",
    paddingBlock: "13px",
    paddingInline: "16px",
    backgroundColor: "accent",
    color: "bg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accent",
    borderStartStartRadius: "10px",
    borderStartEndRadius: "10px",
    borderEndStartRadius: "10px",
    borderEndEndRadius: "10px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "900",
    "& svg": { inlineSize: "20px", blockSize: "20px" },
    _hover: { backgroundColor: "accentHover", borderColor: "accentHover" },
    _disabled: { cursor: "not-allowed", opacity: "0.55" },
  }),
  effortCheckIn: css({
    display: "grid",
    justifyItems: "center",
    gap: "13px",
    paddingBlock: "20px",
    paddingInline: "16px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accent",
    borderStartStartRadius: "12px",
    borderStartEndRadius: "12px",
    borderEndStartRadius: "12px",
    borderEndEndRadius: "12px",
    boxShadow: "0 16px 40px rgba(0, 0, 0, 0.24)",
  }),
  effortCompleteIcon: css({
    inlineSize: "38px",
    blockSize: "38px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "accent",
    color: "bg",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    "& svg": { inlineSize: "20px", blockSize: "20px" },
  }),
  effortHeading: css({
    display: "grid",
    justifyItems: "center",
    gap: "4px",
    textAlign: "center",
    "& h2": { marginBlock: "0", marginInline: "0", fontSize: "18px", fontWeight: "900" },
    "& p": { marginBlock: "0", marginInline: "0", color: "fgMuted", fontSize: "13px" },
  }),
  effortScale: css({
    inlineSize: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
    gap: "7px",
  }),
  effortButton: css({
    minInlineSize: "0",
    minBlockSize: "48px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: "0",
    paddingInline: "0",
    backgroundColor: "cardElevated",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "900",
    transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    _hover: { backgroundColor: "accent", borderColor: "accent", color: "bg" },
    _focusVisible: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
      outline: "none",
    },
    _disabled: { cursor: "not-allowed", opacity: "0.55" },
  }),
  effortScaleLabels: css({
    inlineSize: "100%",
    display: "flex",
    justifyContent: "space-between",
    color: "fgSubtle",
    fontSize: "10px",
    fontWeight: "750",
    textTransform: "uppercase",
  }),
  effortSkipButton: css({
    minBlockSize: "36px",
    paddingBlock: "6px",
    paddingInline: "10px",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "800",
  }),
  completedSetsSection: css({
    display: "grid",
    gap: "9px",
  }),
  completedSetCount: css({
    minInlineSize: "26px",
    blockSize: "26px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: "7px",
    backgroundColor: "card",
    color: "fgMuted",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    fontSize: "11px",
    fontWeight: "850",
  }),
  focusedSetList: css({
    display: "grid",
    gap: "6px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  focusedSetRow: css({
    minBlockSize: "50px",
    display: "grid",
    gridTemplateColumns: "30px minmax(0, 1fr) auto 30px",
    gap: "8px",
    alignItems: "center",
    paddingBlock: "7px",
    paddingInline: "9px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  focusedSetNumber: css({
    inlineSize: "28px",
    blockSize: "28px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "accentSoft",
    color: "accent",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    fontSize: "11px",
    fontWeight: "900",
  }),
  focusedSetSummary: css({
    overflow: "hidden",
    color: "fg",
    fontSize: "13px",
    fontWeight: "800",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  effortBadge: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    color: "warning",
    fontSize: "11px",
    fontWeight: "850",
    "& svg": { inlineSize: "13px", blockSize: "13px" },
  }),
  exercisePager: css({
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "10px",
    paddingBlockStart: "12px",
    borderBlockStartWidth: "1px",
    borderBlockEndWidth: "0",
    borderInlineWidth: "0",
    borderStyle: "solid",
    borderColor: "lineMuted",
    "& button": {
      minInlineSize: "0",
      minBlockSize: "52px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "start",
      gap: "7px",
      paddingBlock: "10px",
      paddingInline: "4px",
      backgroundColor: "transparent",
      color: "fg",
      borderBlockWidth: "0",
      borderInlineWidth: "0",
      cursor: "pointer",
      "& svg": { inlineSize: "16px", blockSize: "16px" },
      "& span": { minInlineSize: "0", display: "grid", gap: "3px", textAlign: "start" },
      "& small": {
        color: "fgSubtle",
        fontSize: "9px",
        fontWeight: "800",
        lineHeight: "1",
        textTransform: "uppercase",
      },
      "& strong": {
        overflow: "hidden",
        fontSize: "12px",
        fontWeight: "850",
        lineHeight: "1.15",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.35" },
    },
    "& button:last-child": {
      justifyContent: "end",
      "& span": { textAlign: "end" },
    },
  }),
  staleWorkoutWarning: css({
    display: "grid",
    gridTemplateColumns: "24px minmax(0, 1fr)",
    gap: "10px",
    alignItems: "start",
    paddingBlock: "12px",
    paddingInline: "12px",
    backgroundColor: "orangeSoft",
    color: "warning",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "orange",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "12px",
    lineHeight: "1.4",
    "& span": { display: "grid", gap: "3px" },
    "& strong": { color: "fg", fontSize: "13px" },
  }),
  staleWorkoutIcon: css({
    inlineSize: "20px",
    blockSize: "20px",
    marginBlockStart: "1px",
  }),
  sessionHeader: css({
    display: "grid",
    gap: "12px",
    gridTemplateColumns: {
      base: "1fr",
      sm: "minmax(0, 1fr) auto",
    },
    alignItems: "start",
  }),
  sessionHeading: css({
    display: "grid",
    gap: "4px",
  }),
  sessionStatus: css({
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "12px",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    textTransform: "uppercase",
  }),
  sessionTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "24px", sm: "30px" },
    fontWeight: "800",
    lineHeight: "1.05",
  }),
  sessionMeta: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    fontWeight: "700",
    lineHeight: "1.35",
  }),
  saveStatus: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "11px",
    fontWeight: "750",
    lineHeight: "1.2",
  }),
  saveStatusIcon: css({
    inlineSize: "14px",
    blockSize: "14px",
  }),
  sessionProgress: css({
    display: "grid",
    gap: "8px",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "bgSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  sessionProgressText: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: "6px",
    color: "fgMuted",
    fontSize: "11px",
    fontWeight: "700",
    lineHeight: "1.25",
    "& strong": { color: "fg", fontSize: "12px" },
  }),
  restTimerPill: cva({
    base: {
      position: "fixed",
      zIndex: "21",
      insetInlineStart: "16px",
      insetInlineEnd: "16px",
      inlineSize: "fit-content",
      maxInlineSize: "calc(100% - 32px)",
      marginInline: "auto",
      display: "flex",
      alignItems: "center",
      gap: "6px",
      paddingBlock: "6px",
      paddingInlineStart: "14px",
      paddingInlineEnd: "6px",
      backgroundColor: "card",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderColor: "line",
      borderStartStartRadius: "999px",
      borderStartEndRadius: "999px",
      borderEndStartRadius: "999px",
      borderEndEndRadius: "999px",
      boxShadow: "0 12px 32px rgba(0, 0, 0, 0.34)",
    },
    variants: {
      focused: {
        true: {
          insetBlockEnd: { base: "calc(18px + env(safe-area-inset-bottom))", md: "24px" },
        },
        false: {
          insetBlockEnd: {
            base: "calc(96px + env(safe-area-inset-bottom))",
            md: "24px",
          },
        },
      },
    },
    defaultVariants: { focused: false },
  }),
  restTimerPillMain: css({
    minBlockSize: "44px",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    paddingBlock: "4px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "fg",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
  }),
  restTimerPillIcon: css({
    inlineSize: "18px",
    blockSize: "18px",
    flexShrink: "0",
    color: "accent",
  }),
  restTimerPillLabel: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "800",
    letterSpacing: "0",
    lineHeight: "1",
    textTransform: "uppercase",
  }),
  restTimerPillTime: css({
    color: "fg",
    fontSize: "16px",
    fontWeight: "900",
    lineHeight: "1",
    fontVariantNumeric: "tabular-nums",
  }),
  restTimerPillSkip: css({
    inlineSize: "36px",
    blockSize: "36px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: "0",
    backgroundColor: "cardElevated",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    cursor: "pointer",
    transition: "background-color 120ms ease, color 120ms ease",
    _hover: {
      backgroundColor: "surfacePressed",
      color: "fg",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.55",
    },
  }),
  exerciseHeading: css({
    display: "grid",
    gap: "4px",
  }),
  exerciseName: css({
    color: "fg",
    fontSize: "16px",
    fontWeight: "800",
    lineHeight: "1.2",
  }),
  exerciseMeta: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.3",
  }),
  setActionButton: css({
    inlineSize: "30px",
    blockSize: "30px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: "0",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    _hover: {
      backgroundColor: "cardElevated",
      borderColor: "lineMuted",
      color: "fg",
    },
    _focusVisible: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
      outline: "none",
    },
  }),
  setActionIcon: css({
    inlineSize: "16px",
    blockSize: "16px",
    flexShrink: "0",
  }),
  setFields: css({
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
  }),
  setField: css({
    minInlineSize: "0",
    display: "grid",
    gap: "6px",
  }),
  setLabel: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  setInput: css({
    inlineSize: "100%",
    minBlockSize: "44px",
    boxSizing: "border-box",
    paddingBlock: "10px",
    paddingInline: "10px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    fontWeight: "700",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  planNameField: css({
    display: "grid",
    gap: "7px",
  }),
  planNameInput: css({
    inlineSize: "100%",
    minBlockSize: "46px",
    boxSizing: "border-box",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    fontWeight: "700",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  setEditForm: css({
    display: "grid",
    gap: "14px",
  }),
  effortEditField: css({
    minInlineSize: "0",
    display: "grid",
    gap: "8px",
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "0",
    paddingInline: "0",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    "& legend": {
      marginBlockEnd: "8px",
      color: "fgMuted",
      fontSize: "12px",
      fontWeight: "800",
    },
    "& > span": { color: "fgSubtle", fontSize: "11px", fontWeight: "650" },
  }),
  effortEditScale: css({
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
    gap: "7px",
  }),
  effortEditButton: cva({
    base: {
      minInlineSize: "0",
      minBlockSize: "44px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      paddingBlock: "0",
      paddingInline: "0",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "999px",
      borderStartEndRadius: "999px",
      borderEndStartRadius: "999px",
      borderEndEndRadius: "999px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "900",
    },
    variants: {
      selected: {
        true: { backgroundColor: "accent", borderColor: "accent", color: "bg" },
        false: { backgroundColor: "cardElevated", borderColor: "line", color: "fgMuted" },
      },
    },
    defaultVariants: { selected: false },
  }),
  formHeader: css({
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "12px",
  }),
  formHeading: css({
    display: "grid",
    gap: "5px",
  }),
  formTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  formDescription: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.4",
  }),
  formActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "1fr",
    flexWrap: "wrap",
    gap: "10px",
  }),
  dialogOverlay: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "30",
    backgroundColor: "rgba(13, 17, 23, 0.78)",
    backdropFilter: "blur(8px)",
  }),
  dialogViewport: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "31",
    display: "grid",
    placeItems: "center",
    paddingBlock: "16px",
    paddingInline: "16px",
    pointerEvents: "none",
  }),
  setDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "520px",
    maxBlockSize: "calc(100vb - 32px)",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  exerciseDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "520px",
    maxBlockSize: "calc(100vb - 32px)",
    overflowBlock: "auto",
    display: "grid",
    gap: "14px",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  exercisePickerList: css({
    display: "grid",
    gap: "10px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  exercisePickerItem: css({
    display: "grid",
    gap: "10px",
    gridTemplateColumns: {
      base: "minmax(0, 1fr)",
      sm: "minmax(0, 1fr) auto",
    },
    alignItems: "center",
    paddingBlock: "12px",
    paddingInline: "12px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  visuallyHidden: css({
    srOnly: true,
  }),
};
