import { css, cva } from "styled-system/css";

export const styles = {
  root: css({
    minBlockSize: "calc(100svh - 28px)",
    display: "grid",
    alignContent: "start",
    gap: "16px",
    paddingBlockEnd: "24px",
  }),
  topBar: css({
    position: "sticky",
    zIndex: "10",
    insetBlockStart: "0",
    minBlockSize: "54px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
    gap: "8px",
    alignItems: "center",
    paddingBlock: "7px",
    backgroundColor: "rgba(13, 17, 23, 0.94)",
    borderBlockEndWidth: "1px",
    borderInlineWidth: "0",
    borderStyle: "solid",
    borderColor: "lineMuted",
    backdropFilter: "blur(14px)",
  }),
  backButton: css({
    minBlockSize: "40px",
    display: "inline-flex",
    alignItems: "center",
    justifySelf: "start",
    gap: "5px",
    paddingBlock: "7px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "fg",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "800",
    "& svg": { inlineSize: "18px", blockSize: "18px" },
  }),
  topBarTitle: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  topBarSpacer: css({
    minInlineSize: "40px",
  }),
  hero: css({
    display: "grid",
    gap: "6px",
    paddingBlockStart: "4px",
    "& p": {
      marginBlock: "0",
      marginInline: "0",
    },
    "& > p:first-child": {
      color: "accent",
      fontSize: "11px",
      fontWeight: "850",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
    },
    "& > p:last-child": {
      maxInlineSize: "500px",
      color: "fgMuted",
      fontSize: "14px",
      fontWeight: "650",
      lineHeight: "1.45",
    },
  }),
  title: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "30px", sm: "38px" },
    fontWeight: "900",
    lineHeight: "1.02",
    textWrap: "balance",
  }),
  summaryGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    overflow: "hidden",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "10px",
    borderStartEndRadius: "10px",
    borderEndStartRadius: "10px",
    borderEndEndRadius: "10px",
  }),
  summaryMetric: css({
    minInlineSize: "0",
    display: "grid",
    justifyItems: "center",
    gap: "5px",
    paddingBlock: "14px",
    paddingInline: "6px",
    textAlign: "center",
    "&:not(:last-child)": {
      borderInlineEndWidth: "1px",
      borderInlineEndStyle: "solid",
      borderInlineEndColor: "lineMuted",
    },
    "& svg": {
      inlineSize: "17px",
      blockSize: "17px",
      color: "accent",
    },
    "& strong": {
      color: "fg",
      fontSize: "20px",
      fontWeight: "900",
      lineHeight: "1",
      fontVariantNumeric: "tabular-nums",
    },
    "& span": {
      color: "fgMuted",
      fontSize: "10px",
      fontWeight: "800",
      lineHeight: "1.1",
      textTransform: "uppercase",
    },
  }),
  completionNotice: cva({
    base: {
      display: "grid",
      gridTemplateColumns: "20px minmax(0, 1fr)",
      gap: "9px",
      alignItems: "center",
      paddingBlock: "11px",
      paddingInline: "12px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      fontSize: "12px",
      fontWeight: "750",
      lineHeight: "1.35",
      "& svg": { inlineSize: "18px", blockSize: "18px" },
    },
    variants: {
      incomplete: {
        true: {
          backgroundColor: "orangeSoft",
          borderColor: "orange",
          color: "warning",
        },
        false: {
          backgroundColor: "accentSoft",
          borderColor: "accentSoft",
          color: "accent",
        },
      },
    },
    defaultVariants: { incomplete: false },
  }),
  section: css({
    display: "grid",
    gap: "10px",
  }),
  sectionHeader: css({
    display: "grid",
    gap: "4px",
    "& h2": {
      marginBlock: "0",
      marginInline: "0",
      color: "fg",
      fontSize: "18px",
      fontWeight: "900",
      lineHeight: "1.15",
    },
    "& p": {
      marginBlock: "0",
      marginInline: "0",
      color: "fgMuted",
      fontSize: "12px",
      lineHeight: "1.4",
    },
  }),
  exerciseList: css({
    display: "grid",
    gap: "10px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  exerciseCard: css({
    display: "grid",
    gap: "12px",
    paddingBlock: "13px",
    paddingInline: "13px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "10px",
    borderStartEndRadius: "10px",
    borderEndStartRadius: "10px",
    borderEndEndRadius: "10px",
  }),
  exerciseHeader: css({
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "10px",
  }),
  exerciseIdentity: css({
    minInlineSize: "0",
    display: "grid",
    gridTemplateColumns: "30px minmax(0, 1fr)",
    gap: "9px",
    alignItems: "center",
    "& > span": {
      inlineSize: "30px",
      blockSize: "30px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "accentSoft",
      color: "accent",
      borderStartStartRadius: "999px",
      borderStartEndRadius: "999px",
      borderEndStartRadius: "999px",
      borderEndEndRadius: "999px",
      fontSize: "11px",
      fontWeight: "900",
    },
    "& div": { minInlineSize: "0", display: "grid", gap: "3px" },
    "& h3": {
      overflow: "hidden",
      marginBlock: "0",
      marginInline: "0",
      color: "fg",
      fontSize: "15px",
      fontWeight: "850",
      lineHeight: "1.15",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& p": {
      marginBlock: "0",
      marginInline: "0",
      color: "fgMuted",
      fontSize: "11px",
      fontWeight: "700",
      lineHeight: "1.2",
    },
  }),
  averageEffort: css({
    flexShrink: "0",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    paddingBlock: "5px",
    paddingInline: "7px",
    backgroundColor: "orangeSoft",
    color: "warning",
    borderStartStartRadius: "999px",
    borderStartEndRadius: "999px",
    borderEndStartRadius: "999px",
    borderEndEndRadius: "999px",
    fontSize: "10px",
    fontWeight: "850",
    lineHeight: "1",
    "& svg": { inlineSize: "12px", blockSize: "12px" },
  }),
  setList: css({
    display: "grid",
    gap: "6px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  setRow: css({
    minBlockSize: "38px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "8px",
    alignItems: "center",
    paddingBlock: "7px",
    paddingInline: "9px",
    backgroundColor: "bgSoft",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "7px",
    borderStartEndRadius: "7px",
    borderEndStartRadius: "7px",
    borderEndEndRadius: "7px",
    fontSize: "12px",
    fontWeight: "750",
    lineHeight: "1.3",
  }),
  setEffort: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "3px",
    color: "warning",
    fontSize: "10px",
    fontWeight: "850",
    "& svg": { inlineSize: "11px", blockSize: "11px" },
  }),
  emptySets: css({
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "9px",
    paddingInline: "10px",
    backgroundColor: "bgSoft",
    color: "fgSubtle",
    borderStartStartRadius: "7px",
    borderStartEndRadius: "7px",
    borderEndStartRadius: "7px",
    borderEndEndRadius: "7px",
    fontSize: "12px",
    fontWeight: "700",
  }),
  confidenceField: css({
    minInlineSize: "0",
    display: "grid",
    gap: "8px",
    marginBlock: "0",
    marginInline: "0",
    paddingBlockStart: "11px",
    paddingBlockEnd: "0",
    paddingInline: "0",
    borderBlockStartWidth: "1px",
    borderBlockEndWidth: "0",
    borderInlineWidth: "0",
    borderStyle: "solid",
    borderColor: "lineMuted",
  }),
  confidenceHeading: css({
    inlineSize: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    marginBlockEnd: "8px",
    paddingInline: "0",
    color: "fgMuted",
    fontSize: "11px",
    fontWeight: "800",
    lineHeight: "1.2",
    "& small": { color: "fgSubtle", fontSize: "10px", fontWeight: "750" },
  }),
  confidenceStars: css({
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(0, 44px))",
    gap: "7px",
  }),
  confidenceStar: cva({
    base: {
      minInlineSize: "0",
      blockSize: "42px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      paddingBlock: "0",
      paddingInline: "0",
      backgroundColor: "cardElevated",
      color: "fgSubtle",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderColor: "lineMuted",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      "& svg": { inlineSize: "19px", blockSize: "19px" },
      _hover: { borderColor: "accent", color: "accent" },
      _focusVisible: {
        borderColor: "accent",
        boxShadow: "0 0 0 3px token(colors.accentSoft)",
        outline: "none",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    variants: {
      filled: {
        true: {
          backgroundColor: "accentSoft",
          borderColor: "accent",
          color: "accent",
          "& svg": { fill: "currentColor" },
        },
      },
    },
    defaultVariants: { filled: false },
  }),
  confidenceHint: css({
    color: "fgSubtle",
    fontSize: "10px",
    fontWeight: "650",
    lineHeight: "1.3",
  }),
  saveBar: css({
    position: "sticky",
    zIndex: "9",
    insetBlockEnd: "0",
    display: "grid",
    gap: "6px",
    paddingBlockStart: "20px",
    paddingBlockEnd: "calc(10px + env(safe-area-inset-bottom))",
    backgroundImage:
      "linear-gradient(to bottom, rgba(13, 17, 23, 0), token(colors.bg) 24px, token(colors.bg))",
    "& small": {
      color: "fgSubtle",
      fontSize: "10px",
      fontWeight: "650",
      lineHeight: "1.3",
      textAlign: "center",
    },
  }),
  saveButton: css({
    minBlockSize: "56px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "9px",
    paddingBlock: "12px",
    paddingInline: "16px",
    backgroundColor: "accent",
    color: "bg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accent",
    borderStartStartRadius: "10px",
    borderStartEndRadius: "10px",
    borderEndStartRadius: "10px",
    borderEndEndRadius: "10px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "900",
    "& svg": { inlineSize: "20px", blockSize: "20px" },
    _hover: { backgroundColor: "accentHover", borderColor: "accentHover" },
    _disabled: { cursor: "not-allowed", opacity: "0.6" },
  }),
};
