import { css, cva } from "styled-system/css";

export const styles = {
  triggerButton: css({
    inlineSize: "48px",
    blockSize: "48px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    _hover: {
      backgroundColor: "card",
      color: "fg",
    },
    _focusVisible: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
      outline: "none",
    },
  }),
  iconButton: css({
    inlineSize: "40px",
    blockSize: "40px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    _hover: {
      backgroundColor: "cardElevated",
      color: "fg",
    },
  }),
  button: cva({
    base: {
      minBlockSize: "44px",
      inlineSize: { base: "100%", sm: "auto" },
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      paddingBlock: "10px",
      paddingInline: "14px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "800",
      lineHeight: "1",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      _disabled: {
        cursor: "not-allowed",
        opacity: "0.55",
      },
    },
    variants: {
      variant: {
        danger: {
          backgroundColor: "dangerSoft",
          borderColor: "danger",
          color: "danger",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fg",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  icon: css({
    inlineSize: "18px",
    blockSize: "18px",
    flexShrink: "0",
  }),
  dialogOverlay: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "30",
    backgroundColor: "rgba(13, 17, 23, 0.78)",
    backdropFilter: "blur(8px)",
  }),
  dialogViewport: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "31",
    display: "grid",
    placeItems: "center",
    paddingBlock: "16px",
    paddingInline: "16px",
    pointerEvents: "none",
  }),
  dialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "480px",
    maxBlockSize: "calc(100vb - 32px)",
    display: "grid",
    gap: "16px",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  dialogHeader: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "12px",
    alignItems: "start",
  }),
  dialogHeading: css({
    display: "grid",
    gap: "6px",
  }),
  dialogTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "22px",
    fontWeight: "900",
    lineHeight: "1.1",
  }),
  dialogDescription: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  feedback: css({
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "12px",
    paddingInline: "14px",
    color: "warning",
    backgroundColor: "orangeSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "orange",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "14px",
    fontWeight: "700",
  }),
  section: css({
    display: "grid",
    gap: "14px",
    paddingBlock: "14px",
    paddingInline: "14px",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  sectionText: css({
    display: "grid",
    gap: "6px",
  }),
  sectionTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "17px",
    fontWeight: "900",
    lineHeight: "1.15",
  }),
  sectionDescription: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  confirmDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "420px",
    maxBlockSize: "calc(100vb - 32px)",
    display: "grid",
    gap: "14px",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  confirmTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "danger",
    fontSize: "20px",
    fontWeight: "900",
    lineHeight: "1.2",
  }),
  confirmDescription: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  confirmActions: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "end",
    gap: "8px",
  }),
  visuallyHidden: css({
    srOnly: true,
  }),
};
