import { css, cva } from "styled-system/css";

export const styles = {
  overlay: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "40",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  }),
  viewport: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "40",
    display: "grid",
    placeItems: "center",
    paddingBlock: { base: "0", sm: "24px" },
    paddingInline: { base: "0", sm: "24px" },
    pointerEvents: "none",
  }),
  content: cva({
    base: {
      inlineSize: "calc(100% - 32px)",
      maxInlineSize: "560px",
      maxBlockSize: "calc(100dvb - 32px)",
      display: "flex",
      flexDirection: "column",
      minBlockSize: "0",
      backgroundColor: "card",
      color: "fg",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderColor: "line",
      borderStartStartRadius: "16px",
      borderStartEndRadius: "16px",
      borderEndStartRadius: "16px",
      borderEndEndRadius: "16px",
      pointerEvents: "auto",
      overflow: "hidden",
      outline: "none",
    },
    variants: {
      fullScreen: {
        true: {
          inlineSize: "100%",
          maxInlineSize: "640px",
          blockSize: { base: "100dvb", sm: "min(850px, calc(100dvb - 48px))" },
          maxBlockSize: { base: "100dvb", sm: "calc(100dvb - 48px)" },
          borderStartStartRadius: { base: "0", sm: "16px" },
          borderStartEndRadius: { base: "0", sm: "16px" },
          borderEndStartRadius: { base: "0", sm: "16px" },
          borderEndEndRadius: { base: "0", sm: "16px" },
        },
      },
    },
  }),
  header: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexShrink: "0",
    paddingInline: "20px",
    paddingBlockStart: "max(16px, env(safe-area-inset-top))",
    paddingBlockEnd: "16px",
    borderBlockEnd: "1px solid token(colors.lineMuted)",
  }),
  title: css({
    color: "fg",
    fontSize: "22px",
    fontWeight: "800",
    lineHeight: "1.2",
    overflowWrap: "anywhere",
  }),
  body: css({
    display: "grid",
    alignContent: "start",
    gap: "20px",
    paddingBlock: "20px",
    paddingInline: "20px",
    overflowBlock: "auto",
    overscrollBehaviorBlock: "contain",
    minBlockSize: "0",
    flex: "1",
  }),
  footer: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "end",
    alignItems: "center",
    gap: "10px",
    paddingInline: "20px",
    paddingBlockStart: "14px",
    paddingBlockEnd: "max(16px, env(safe-area-inset-bottom))",
    borderBlockStart: "1px solid token(colors.lineMuted)",
    backgroundColor: "card",
    flexShrink: "0",
  }),
};
