import { css } from "styled-system/css";

export const styles = {
  root: css({
    boxSizing: "border-box",
    inlineSize: "100%",
    maxInlineSize: "960px",
    marginInline: "auto",
    paddingInline: { base: "16px", sm: "24px" },
    paddingBlockStart: { base: "14px", sm: "32px" },
    paddingBlockEnd: { base: "20px", sm: "32px" },
    color: "fg",
    display: "grid",
    gap: "20px",
  }),
  header: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "16px",
    alignItems: "center",
    justifyContent: "space-between",
  }),
  headerText: css({ display: "grid", gap: "8px" }),
  eyebrow: css({
    color: "accent",
    fontSize: "12px",
    fontWeight: "750",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  }),
  title: css({ fontSize: { base: "28px", sm: "40px" }, fontWeight: "800", lineHeight: "1.1" }),
  libraryCount: css({ color: "fgMuted", fontSize: "13px", fontWeight: "650" }),
  templateList: css({
    display: "grid",
    gap: "14px",
    gridTemplateColumns: { base: "minmax(0, 1fr)", md: "repeat(2, minmax(0, 1fr))" },
    listStyle: "none",
    paddingInlineStart: "0",
  }),
  templateCard: css({
    minInlineSize: "0",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "14px",
    borderStartEndRadius: "14px",
    borderEndStartRadius: "14px",
    borderEndEndRadius: "14px",
    overflow: "hidden",
  }),
  cardOpen: css({
    display: "grid",
    gap: "8px",
    inlineSize: "100%",
    paddingBlock: "18px",
    paddingInline: "18px",
    textAlign: "start",
    cursor: "pointer",
    _hover: { backgroundColor: "cardElevated" },
    _focusVisible: { outline: "2px solid token(colors.accent)", outlineOffset: "-3px" },
  }),
  cardHeading: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    color: "fgMuted",
  }),
  templateName: css({
    color: "fg",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1.2",
    overflowWrap: "anywhere",
  }),
  summary: css({ color: "fgMuted", fontSize: "13px", fontWeight: "650", lineHeight: "1.5" }),
  preview: css({
    display: "block",
    color: "fgMuted",
    fontSize: "14px",
    fontWeight: "400",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  }),
  cardFooter: css({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto auto",
    alignItems: "center",
    gap: "6px",
    marginBlockStart: "auto",
    paddingInline: "14px",
    paddingBlock: "12px",
    borderBlockStart: "1px solid token(colors.lineMuted)",
  }),
  lastCompleted: css({
    color: "fgMuted",
    fontSize: "12px",
    lineHeight: "1.5",
    paddingInlineEnd: "6px",
  }),
  sectionTitle: css({ color: "fg", fontSize: "16px", fontWeight: "750", overflowWrap: "anywhere" }),
  resumeBanner: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "14px",
    paddingBlock: "16px",
    paddingInline: "16px",
    backgroundColor: "accentSoft",
    borderInlineStart: "3px solid token(colors.accent)",
    borderStartEndRadius: "10px",
    borderEndEndRadius: "10px",
  }),
  emptyState: css({
    display: "grid",
    justifyItems: "start",
    gap: "14px",
    paddingBlock: "28px",
    paddingInline: "22px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "12px",
    borderStartEndRadius: "12px",
    borderEndStartRadius: "12px",
    borderEndEndRadius: "12px",
  }),
  emptyIcon: css({ inlineSize: "32px", blockSize: "32px", color: "accent" }),
  emptyActions: css({ display: "flex", flexWrap: "wrap", gap: "10px" }),
  actionList: css({ display: "grid", gap: "10px", listStyle: "none", paddingInlineStart: "0" }),
  actionButton: css({
    inlineSize: "100%",
    display: "flex",
    gap: "12px",
    alignItems: "center",
    textAlign: "start",
    minBlockSize: "52px",
    paddingBlock: "14px",
    paddingInline: "14px",
    backgroundColor: "cardElevated",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "10px",
    borderStartEndRadius: "10px",
    borderEndStartRadius: "10px",
    borderEndEndRadius: "10px",
    cursor: "pointer",
    "& > span": { display: "grid", flex: "1", minInlineSize: "0", gap: "5px" },
    "& strong": { overflowWrap: "anywhere" },
    _hover: { backgroundColor: "surfacePressed" },
    _focusVisible: { outline: "2px solid token(colors.accent)", outlineOffset: "2px" },
  }),
  detailList: css({ listStyle: "none", display: "grid", gap: "16px", paddingInlineStart: "0" }),
  detailExercise: css({
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr)",
    gap: "12px",
    paddingBlockEnd: "16px",
    borderBlockEnd: "1px solid token(colors.lineMuted)",
  }),
  exerciseNumber: css({
    color: "accent",
    fontSize: "14px",
    fontWeight: "800",
    paddingBlockStart: "2px",
  }),
  notes: css({
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.5",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    marginBlockStart: "8px",
  }),
};
