import { css } from "styled-system/css";

export const styles = {
  form: css({ display: "grid", gap: "24px", minInlineSize: "0" }),
  footerError: css({ flexBasis: "100%" }),
  list: css({ display: "grid", gap: "16px", listStyle: "none", paddingInlineStart: "0" }),
  exercise: css({
    display: "grid",
    gap: "16px",
    minInlineSize: "0",
    paddingBlock: "16px",
    paddingInline: "14px",
    backgroundColor: "bgSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "12px",
    borderStartEndRadius: "12px",
    borderEndStartRadius: "12px",
    borderEndEndRadius: "12px",
  }),
  heading: css({ display: "flex", alignItems: "center", gap: "10px", minInlineSize: "0" }),
  number: css({
    color: "accent",
    backgroundColor: "accentSoft",
    inlineSize: "30px",
    blockSize: "30px",
    flexShrink: "0",
    display: "grid",
    placeItems: "center",
    fontSize: "13px",
    fontWeight: "800",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  name: css({ fontSize: "16px", fontWeight: "750", flex: "1", overflowWrap: "anywhere" }),
  moveActions: css({ display: "flex", gap: "4px", alignItems: "center" }),
  orderHint: css({ color: "fgMuted", fontSize: "13px", marginInlineEnd: "auto" }),
  fields: css({
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 140px), 1fr))",
  }),
  stepper: css({
    display: "grid",
    gridTemplateColumns: "44px minmax(0, 1fr) 44px",
    gap: "6px",
    alignItems: "center",
  }),
  presets: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    "& button[aria-pressed=true]": {
      borderColor: "accent",
      color: "accent",
      backgroundColor: "accentSoft",
    },
  }),
  notes: css({
    display: "grid",
    gap: "8px",
    "& summary": {
      cursor: "pointer",
      color: "fgMuted",
      fontSize: "14px",
      minBlockSize: "44px",
      paddingBlock: "12px",
    },
  }),
  footerHint: css({ marginInlineEnd: "auto", color: "fgMuted", fontSize: "13px" }),
  fullButton: css({ inlineSize: "100%", display: "grid" }),
};
