import { css, cva } from "styled-system/css";

export const styles = {
  root: css({
    minInlineSize: "0",
  }),
  plot: css({
    position: "relative",
  }),
  chart: css({
    inlineSize: "100%",
    blockSize: "auto",
    display: "block",
    overflow: "visible",
  }),
  gridLine: css({
    stroke: "lineMuted",
    strokeWidth: "1",
    vectorEffect: "non-scaling-stroke",
  }),
  line: css({
    fill: "none",
    stroke: "accent",
    strokeWidth: "3",
    strokeLinejoin: "round",
    strokeLinecap: "round",
    vectorEffect: "non-scaling-stroke",
  }),
  pointTarget: css({
    cursor: "pointer",
    outline: "none",
    "&:focus-visible [data-point-marker]": {
      stroke: "blue",
      strokeWidth: "4",
    },
  }),
  hitArea: css({
    fill: "transparent",
    stroke: "none",
  }),
  point: cva({
    base: {
      strokeWidth: "3",
      vectorEffect: "non-scaling-stroke",
      pointerEvents: "none",
      transitionProperty: "r, stroke-width",
      transitionDuration: "120ms",
      "&[data-active='true']": {
        stroke: "blue",
        strokeWidth: "4",
      },
    },
    variants: {
      record: {
        false: { fill: "card", stroke: "accent" },
        true: { fill: "orange", stroke: "card" },
      },
    },
  }),
  guide: css({
    stroke: "fgSubtle",
    strokeWidth: "1",
    strokeDasharray: "3 4",
    vectorEffect: "non-scaling-stroke",
    pointerEvents: "none",
  }),
  tooltip: css({
    position: "absolute",
    zIndex: "1",
    inlineSize: "max-content",
    maxInlineSize: "min(230px, calc(100% - 16px))",
    display: "grid",
    gap: "8px",
    paddingBlock: "10px",
    paddingInline: "12px",
    backgroundColor: "cardElevated",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 12px 32px rgba(0, 0, 0, 0.34)",
    pointerEvents: "none",
  }),
  tooltipHeading: css({
    display: "grid",
    gap: "2px",
    paddingBlockEnd: "7px",
    borderBlockEndWidth: "1px",
    borderBlockEndStyle: "solid",
    borderBlockEndColor: "lineMuted",
    "& strong": { fontSize: "12px", lineHeight: "1.2" },
    "& span": { color: "fgMuted", fontSize: "10px", fontWeight: "700" },
  }),
  tooltipRow: css({
    minInlineSize: "170px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: "14px",
    fontSize: "11px",
    "& span": { color: "fgMuted" },
    "& strong": { color: "fg", textAlign: "end" },
  }),
  record: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    color: "orange",
    fontSize: "10px",
    fontWeight: "800",
    "& svg": { inlineSize: "12px", blockSize: "12px" },
  }),
  axis: css({
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    color: "fgSubtle",
    fontSize: "10px",
    fontWeight: "700",
  }),
};
