import { css, cva } from "styled-system/css";

export const styles = {
  root: css({
    boxSizing: "border-box",
    inlineSize: "100%",
    maxInlineSize: "960px",
    marginInline: "auto",
    paddingInline: { base: "16px", sm: "24px" },
    paddingBlockStart: { base: "14px", sm: "32px" },
    paddingBlockEnd: { base: "20px", sm: "32px" },
    color: "fg",
  }),
  header: css({
    display: "grid",
    gap: { base: "14px", sm: "18px" },
    alignItems: "end",
    gridTemplateColumns: {
      base: "1fr",
      md: "minmax(0, 1fr) auto",
    },
  }),
  headerText: css({
    display: "grid",
    gap: "8px",
  }),
  eyebrow: css({
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "0",
    textTransform: "uppercase",
  }),
  title: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "28px", sm: "44px" },
    fontWeight: "800",
    lineHeight: "1",
    textWrap: "balance",
  }),
  description: css({
    maxInlineSize: "580px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: { base: "15px", sm: "16px" },
    lineHeight: "1.5",
  }),
  headerActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(0, 1.1fr)",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
  }),
  countBadge: css({
    inlineSize: { base: "100%", sm: "auto" },
    minBlockSize: "48px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    paddingBlock: "10px",
    paddingInline: "14px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  countValue: css({
    color: "accent",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  countLabel: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1",
  }),
  button: cva({
    base: {
      minBlockSize: "44px",
      inlineSize: { base: "100%", sm: "auto" },
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      paddingBlock: "10px",
      paddingInline: "14px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "800",
      lineHeight: "1",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    },
    variants: {
      variant: {
        primary: {
          backgroundColor: "accent",
          borderColor: "accent",
          color: "bg",
          _hover: {
            backgroundColor: "accentHover",
            borderColor: "accentHover",
          },
          _active: {
            backgroundColor: "accentPressed",
            borderColor: "accentPressed",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fg",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
        danger: {
          backgroundColor: "dangerSoft",
          borderColor: "danger",
          color: "danger",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  iconButton: cva({
    base: {
      inlineSize: "42px",
      blockSize: "42px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    },
    variants: {
      variant: {
        ghost: {
          backgroundColor: "transparent",
          borderColor: "lineMuted",
          color: "fgMuted",
          _hover: {
            backgroundColor: "cardElevated",
            color: "fg",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fgMuted",
          _hover: {
            color: "fg",
            backgroundColor: "surfacePressed",
          },
        },
        danger: {
          backgroundColor: "dangerSoft",
          borderColor: "dangerSoft",
          color: "danger",
          _hover: {
            borderColor: "danger",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  icon: css({
    inlineSize: "18px",
    blockSize: "18px",
    flexShrink: "0",
  }),
  feedback: css({
    marginBlockStart: "18px",
    marginBlockEnd: "0",
    marginInline: "0",
    paddingBlock: "12px",
    paddingInline: "14px",
    color: "warning",
    backgroundColor: "orangeSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "orange",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "14px",
    fontWeight: "700",
  }),
  formPanel: css({
    display: "grid",
    gap: "14px",
  }),
  formHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  }),
  formTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  field: css({
    display: "grid",
    gap: "7px",
  }),
  label: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  input: css({
    inlineSize: "100%",
    minBlockSize: "46px",
    boxSizing: "border-box",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  textarea: css({
    inlineSize: "100%",
    minBlockSize: "96px",
    resize: "block",
    boxSizing: "border-box",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    lineHeight: "1.4",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  checkboxField: css({
    display: "flex",
    alignItems: "start",
    gap: "10px",
    cursor: "pointer",
  }),
  checkbox: css({
    inlineSize: "20px",
    blockSize: "20px",
    marginBlockStart: "2px",
    flexShrink: "0",
    accentColor: "token(colors.accent)",
    cursor: "pointer",
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.5",
    },
  }),
  checkboxText: css({
    display: "grid",
    gap: "3px",
  }),
  checkboxHint: css({
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "600",
    lineHeight: "1.35",
  }),
  confidenceField: css({
    minInlineSize: "0",
    display: "grid",
    gap: "8px",
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "0",
    paddingInline: "0",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    borderStyle: "solid",
  }),
  confidenceHint: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "600",
    lineHeight: "1.4",
  }),
  confidenceControl: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
  }),
  confidenceStars: css({
    display: "flex",
    gap: "6px",
  }),
  confidenceStar: cva({
    base: {
      inlineSize: "44px",
      blockSize: "44px",
      display: "grid",
      placeItems: "center",
      backgroundColor: "cardElevated",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderColor: "lineMuted",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      color: "fgSubtle",
      cursor: "pointer",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
      "& svg": {
        inlineSize: "20px",
        blockSize: "20px",
      },
      _hover: {
        borderColor: "accent",
        color: "accent",
      },
      _focusWithin: {
        outline: "2px solid token(colors.accent)",
        outlineOffset: "2px",
      },
    },
    variants: {
      filled: {
        true: {
          backgroundColor: "accentSoft",
          borderColor: "accent",
          color: "accent",
          "& svg": {
            fill: "currentColor",
          },
        },
      },
    },
  }),
  clearConfidenceButton: css({
    minBlockSize: "44px",
    paddingBlock: "8px",
    paddingInline: "4px",
    backgroundColor: "transparent",
    color: "fgMuted",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    borderStyle: "solid",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "800",
    _hover: {
      color: "fg",
    },
  }),
  confidenceEndpoints: css({
    inlineSize: "244px",
    maxInlineSize: "100%",
    display: "flex",
    justifyContent: "space-between",
    color: "fgSubtle",
    fontSize: "11px",
    fontWeight: "700",
    lineHeight: "1",
  }),
  formActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "1fr",
    flexWrap: "wrap",
    gap: "10px",
  }),
  emptyState: css({
    display: "grid",
    justifyItems: "start",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
    paddingBlock: { base: "20px", sm: "24px" },
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  emptyIcon: css({
    inlineSize: "32px",
    blockSize: "32px",
    color: "accent",
  }),
  emptyTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "22px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  emptyDescription: css({
    maxInlineSize: "520px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "15px",
    lineHeight: "1.45",
  }),
  exerciseList: css({
    display: "grid",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
    marginBlockEnd: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  exerciseCard: css({
    display: "grid",
    gap: { base: "12px", sm: "14px" },
    gridTemplateColumns: {
      base: "minmax(0, 1fr) auto",
      sm: "minmax(0, 1fr) auto",
    },
    paddingBlock: { base: "14px", sm: "16px" },
    paddingInline: "16px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  exerciseDetailButton: css({
    minInlineSize: "0",
    display: "grid",
    gap: "10px",
    paddingBlock: "0",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "inherit",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    borderStyle: "solid",
    cursor: "pointer",
    textAlign: "start",
    _focusVisible: {
      outline: "2px solid token(colors.accent)",
      outlineOffset: "4px",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
    },
  }),
  exerciseHeading: css({
    display: "grid",
    gap: "4px",
  }),
  exerciseName: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "19px",
    fontWeight: "800",
    lineHeight: "1.15",
  }),
  equipment: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgSubtle",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.2",
  }),
  exerciseMetaRow: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    alignItems: "center",
  }),
  confidenceBadge: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    color: "accent",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
    "& svg": {
      inlineSize: "13px",
      blockSize: "13px",
      fill: "currentColor",
    },
  }),
  muscleGroups: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  }),
  muscleGroup: css({
    paddingBlock: "5px",
    paddingInline: "8px",
    color: "accent",
    backgroundColor: "accentSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accentSoft",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  muscleGroupMuted: css({
    color: "fgSubtle",
    fontSize: "13px",
    fontWeight: "700",
  }),
  notes: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  cardActions: css({
    display: "flex",
    gap: "8px",
    alignItems: "start",
    justifyContent: {
      base: "end",
      sm: "end",
    },
  }),
  detailRoot: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "26",
    boxSizing: "border-box",
    display: "grid",
    alignContent: "start",
    gap: "18px",
    overflowBlock: "auto",
    inlineSize: "100%",
    paddingBlockStart: "calc(14px + env(safe-area-inset-top))",
    paddingBlockEnd: "calc(24px + env(safe-area-inset-bottom))",
    paddingInline: "16px",
    backgroundColor: "bg",
    color: "fg",
  }),
  detailTopBar: css({
    inlineSize: "100%",
    maxInlineSize: "430px",
    marginInline: "auto",
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr) 42px",
    alignItems: "center",
    gap: "10px",
  }),
  detailTopTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "16px",
    fontWeight: "800",
    lineHeight: "1",
    textAlign: "center",
  }),
  detailHero: css({
    inlineSize: "100%",
    maxInlineSize: "430px",
    marginInline: "auto",
    display: "grid",
    gridTemplateColumns: { base: "112px minmax(0, 1fr)", sm: "124px minmax(0, 1fr)" },
    gap: "16px",
    alignItems: "center",
  }),
  exerciseIllustration: css({
    aspectRatio: "1",
    display: "grid",
    placeItems: "center",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.04)",
  }),
  exerciseIllustrationIcon: css({
    inlineSize: "48px",
    blockSize: "48px",
    color: "accent",
    filter: "drop-shadow(0 0 14px rgba(167, 240, 27, 0.22))",
  }),
  detailSummary: css({
    minInlineSize: "0",
    display: "grid",
    gap: "10px",
  }),
  detailName: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "27px", sm: "32px" },
    fontWeight: "900",
    lineHeight: "1.05",
    textWrap: "balance",
  }),
  detailPills: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  }),
  detailPill: cva({
    base: {
      minBlockSize: "30px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "6px",
      paddingBlock: "6px",
      paddingInline: "10px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      fontSize: "13px",
      fontWeight: "800",
      lineHeight: "1",
    },
    variants: {
      tone: {
        accent: {
          backgroundColor: "accentSoft",
          borderColor: "accentSoft",
          color: "accent",
        },
        muted: {
          backgroundColor: "cardElevated",
          borderColor: "lineMuted",
          color: "fg",
        },
        equipment: {
          backgroundColor: "cardElevated",
          borderColor: "lineMuted",
          color: "fgMuted",
        },
        confidence: {
          backgroundColor: "accentSoft",
          borderColor: "accentSoft",
          color: "accent",
          "& svg": {
            fill: "currentColor",
          },
        },
      },
    },
    defaultVariants: {
      tone: "muted",
    },
  }),
  detailPillIcon: css({
    inlineSize: "15px",
    blockSize: "15px",
    flexShrink: "0",
  }),
  detailSection: css({
    inlineSize: "100%",
    maxInlineSize: "430px",
    marginInline: "auto",
    display: "grid",
    gap: "10px",
  }),
  detailSectionHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  }),
  detailSectionTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "18px",
    fontWeight: "900",
    lineHeight: "1.15",
  }),
  detailTextButton: css({
    minBlockSize: "34px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: "6px",
    paddingInline: "0",
    backgroundColor: "transparent",
    color: "accent",
    borderBlockWidth: "0",
    borderInlineWidth: "0",
    borderStyle: "solid",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "900",
    lineHeight: "1",
  }),
  performanceCard: css({
    inlineSize: "100%",
    maxInlineSize: "430px",
    marginInline: "auto",
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    paddingBlock: "16px",
    paddingInline: "10px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.04)",
  }),
  performanceMetric: css({
    minInlineSize: "0",
    display: "grid",
    gap: "6px",
    justifyItems: "center",
    paddingInline: "8px",
    textAlign: "center",
    "&:not(:last-child)": {
      borderInlineEndWidth: "1px",
      borderInlineEndStyle: "solid",
      borderInlineEndColor: "lineMuted",
    },
  }),
  performanceLabel: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1",
  }),
  performanceValue: css({
    color: "fg",
    fontSize: { base: "17px", sm: "20px" },
    fontWeight: "900",
    lineHeight: "1",
  }),
  summaryMetricIcon: css({
    inlineSize: "18px",
    blockSize: "18px",
    color: "accent",
  }),
  exerciseNotes: css({
    inlineSize: "100%",
    maxInlineSize: "430px",
    marginInline: "auto",
    display: "grid",
    gridTemplateColumns: "20px minmax(0, 1fr)",
    gap: "10px",
    paddingBlock: "12px",
    paddingInline: "14px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    "& strong": { color: "fg", fontSize: "13px" },
    "& p": {
      marginBlockStart: "4px",
      marginBlockEnd: "0",
      marginInline: "0",
      color: "fgMuted",
      fontSize: "13px",
      lineHeight: "1.4",
    },
  }),
  exerciseNotesIcon: css({
    inlineSize: "18px",
    blockSize: "18px",
    marginBlockStart: "1px",
    color: "accent",
  }),
  detailSectionDescription: css({
    marginBlockStart: "4px",
    marginBlockEnd: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "13px",
    lineHeight: "1.35",
  }),
  detailSectionIcon: css({
    inlineSize: "20px",
    blockSize: "20px",
    color: "accent",
    flexShrink: "0",
  }),
  workoutPerformanceCard: css({
    display: "grid",
    gap: "12px",
    paddingBlock: "14px",
    paddingInline: "14px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  workoutPerformanceHeader: css({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "start",
    gap: "12px",
    "& > div": { minInlineSize: "0", display: "grid", gap: "3px" },
    "& strong": { color: "fg", fontSize: "15px", lineHeight: "1.2" },
    "& > div > span": { color: "fgMuted", fontSize: "12px", fontWeight: "700" },
  }),
  restBadge: css({
    minBlockSize: "28px",
    display: "inline-flex",
    alignItems: "center",
    flexShrink: "0",
    paddingBlock: "5px",
    paddingInline: "8px",
    backgroundColor: "cardElevated",
    color: "fgMuted",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "11px",
    fontWeight: "800",
  }),
  workoutPerformanceMeta: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "12px",
    fontWeight: "700",
  }),
  performanceSetList: css({
    display: "grid",
    gap: "7px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  performanceSetRow: css({
    minBlockSize: "44px",
    display: "grid",
    gridTemplateColumns: "30px minmax(0, 1fr)",
    gap: "10px",
    alignItems: "center",
    paddingBlock: "8px",
    paddingInline: "10px",
    backgroundColor: "cardElevated",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    "& > span:last-child": { minInlineSize: "0", display: "grid", gap: "3px" },
    "& strong": { color: "fg", fontSize: "15px" },
    "& small": { color: "fgMuted", fontSize: "11px", lineHeight: "1.3" },
  }),
  performanceSetNumber: css({
    inlineSize: "28px",
    blockSize: "28px",
    display: "grid",
    placeItems: "center",
    backgroundColor: "accentSoft",
    color: "accent",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "12px",
    fontWeight: "900",
  }),
  performanceNotes: css({
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr)",
    gap: "8px",
    alignItems: "start",
    color: "fgMuted",
    fontSize: "12px",
    lineHeight: "1.4",
    "& svg": { inlineSize: "15px", blockSize: "15px", color: "accent" },
  }),
  progressCard: css({
    display: "grid",
    gap: "14px",
    paddingBlock: "14px",
    paddingInline: "12px",
    overflow: "hidden",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  progressControls: css({
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
    alignItems: "end",
  }),
  progressField: css({
    minInlineSize: "0",
    display: "grid",
    gap: "5px",
    color: "fgMuted",
    fontSize: "10px",
    fontWeight: "800",
    "& select": {
      minInlineSize: "0",
      inlineSize: "100%",
      minBlockSize: "38px",
      paddingBlock: "6px",
      paddingInline: "8px",
      backgroundColor: "cardElevated",
      color: "fg",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderColor: "line",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      fontSize: "12px",
      fontWeight: "800",
    },
  }),
  progressMetricName: css({
    minBlockSize: "38px",
    display: "flex",
    alignItems: "center",
    color: "accent",
    fontSize: "12px",
    fontWeight: "850",
  }),
  progressStats: css({
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "6px",
    "& > div": {
      minInlineSize: "0",
      display: "grid",
      alignContent: "start",
      gap: "5px",
      paddingInline: "6px",
      textAlign: "center",
    },
    "& > div:not(:last-child)": {
      borderInlineEndWidth: "1px",
      borderInlineEndStyle: "solid",
      borderInlineEndColor: "lineMuted",
    },
    "& span": { color: "fgMuted", fontSize: "10px", fontWeight: "750" },
    "& > div > strong:not([class])": {
      color: "fg",
      fontSize: { base: "13px", sm: "16px" },
      fontWeight: "900",
    },
    "& small": { color: "fgSubtle", fontSize: "9px", fontWeight: "700" },
  }),
  progressChange: cva({
    base: {
      display: "inline-flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "3px",
      "& svg": { inlineSize: "13px", blockSize: "13px" },
    },
    variants: {
      trend: {
        positive: { color: "accent" },
        negative: { color: "danger" },
        neutral: { color: "fg" },
      },
    },
  }),
  progressRangeEmpty: css({
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "30px",
    color: "fgMuted",
    fontSize: "13px",
    textAlign: "center",
  }),
  prLegend: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "end",
    gap: "5px",
    color: "fgMuted",
    fontSize: "10px",
    fontWeight: "750",
    "& svg": { inlineSize: "12px", blockSize: "12px", color: "orange" },
  }),
  performanceHistoryList: css({
    display: "grid",
    gap: "8px",
    marginBlock: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  performanceHistoryCard: css({
    display: "grid",
    gap: "10px",
    paddingBlock: "12px",
    paddingInline: "12px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  performanceHistoryHeader: css({
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    alignItems: "start",
    "& > div": { minInlineSize: "0", display: "grid", gap: "2px" },
    "& strong": { color: "fg", fontSize: "13px" },
    "& span": { color: "fgMuted", fontSize: "10px", fontWeight: "700" },
    "& > span": { maxInlineSize: "55%", textAlign: "end" },
  }),
  performanceHistorySets: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    "& span": {
      paddingBlock: "5px",
      paddingInline: "7px",
      backgroundColor: "cardElevated",
      color: "fg",
      borderStartStartRadius: "6px",
      borderStartEndRadius: "6px",
      borderEndStartRadius: "6px",
      borderEndEndRadius: "6px",
      fontSize: "11px",
      fontWeight: "800",
    },
  }),
  performanceHistoryNotes: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "11px",
    lineHeight: "1.35",
  }),
  detailEmpty: css({
    marginBlock: "0",
    marginInline: "0",
    paddingBlock: "16px",
    paddingInline: "14px",
    color: "fgMuted",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "14px",
    fontWeight: "700",
  }),
  detailLogButton: css({
    inlineSize: "100%",
    maxInlineSize: "430px",
    minBlockSize: "54px",
    marginInline: "auto",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "18px",
    paddingBlock: "14px",
    paddingInline: "18px",
    backgroundColor: "accent",
    color: "bg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accent",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    cursor: "pointer",
    fontSize: "18px",
    fontWeight: "900",
    lineHeight: "1",
    boxShadow: "0 16px 36px rgba(167, 240, 27, 0.14)",
    transition: "background-color 120ms ease, border-color 120ms ease, transform 120ms ease",
    _hover: {
      backgroundColor: "accentHover",
      borderColor: "accentHover",
    },
    _active: {
      backgroundColor: "accentPressed",
      borderColor: "accentPressed",
      transform: "translateY(1px)",
    },
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.65",
      transform: "none",
    },
  }),
  detailLogIcon: css({
    inlineSize: "22px",
    blockSize: "22px",
    flexShrink: "0",
  }),
  dialogOverlay: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "30",
    backgroundColor: "rgba(13, 17, 23, 0.78)",
    backdropFilter: "blur(8px)",
  }),
  dialogViewport: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "31",
    display: "grid",
    placeItems: "center",
    paddingBlock: "16px",
    paddingInline: "16px",
    pointerEvents: "none",
  }),
  formDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "520px",
    maxBlockSize: "calc(100vb - 32px)",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  dialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "420px",
    maxBlockSize: "calc(100vb - 32px)",
    display: "grid",
    gap: "14px",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  dialogTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "danger",
    fontSize: "20px",
    fontWeight: "900",
    lineHeight: "1.2",
  }),
  dialogDescription: css({
    display: "grid",
    gap: "4px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  dialogActions: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "end",
    gap: "8px",
  }),
  visuallyHidden: css({
    srOnly: true,
  }),
};
