import { css, cva } from "styled-system/css";

export const styles = {
  root: css({
    boxSizing: "border-box",
    inlineSize: "100%",
    maxInlineSize: "960px",
    marginInline: "auto",
    paddingInline: { base: "16px", sm: "24px" },
    paddingBlockStart: { base: "14px", sm: "32px" },
    paddingBlockEnd: { base: "20px", sm: "32px" },
    color: "fg",
  }),
  header: css({
    display: "grid",
    gap: { base: "14px", sm: "18px" },
    alignItems: "end",
    gridTemplateColumns: {
      base: "1fr",
      md: "minmax(0, 1fr) auto",
    },
  }),
  headerText: css({
    display: "grid",
    gap: "8px",
  }),
  eyebrow: css({
    marginBlock: "0",
    marginInline: "0",
    color: "accent",
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "0",
    textTransform: "uppercase",
  }),
  title: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: { base: "28px", sm: "44px" },
    fontWeight: "800",
    lineHeight: "1",
    textWrap: "balance",
  }),
  description: css({
    maxInlineSize: "580px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: { base: "15px", sm: "16px" },
    lineHeight: "1.5",
  }),
  headerActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(0, 1.1fr)",
    flexWrap: "wrap",
    gap: "10px",
    alignItems: "center",
  }),
  countBadge: css({
    inlineSize: { base: "100%", sm: "auto" },
    minBlockSize: "48px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    paddingBlock: "10px",
    paddingInline: "14px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  countValue: css({
    color: "accent",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  countLabel: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1",
  }),
  button: cva({
    base: {
      minBlockSize: "44px",
      inlineSize: { base: "100%", sm: "auto" },
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      paddingBlock: "10px",
      paddingInline: "14px",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "800",
      lineHeight: "1",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    },
    variants: {
      variant: {
        primary: {
          backgroundColor: "accent",
          borderColor: "accent",
          color: "bg",
          _hover: {
            backgroundColor: "accentHover",
            borderColor: "accentHover",
          },
          _active: {
            backgroundColor: "accentPressed",
            borderColor: "accentPressed",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fg",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
        danger: {
          backgroundColor: "dangerSoft",
          borderColor: "danger",
          color: "danger",
          _hover: {
            backgroundColor: "surfacePressed",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  iconButton: cva({
    base: {
      inlineSize: "42px",
      blockSize: "42px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      borderBlockWidth: "1px",
      borderInlineWidth: "1px",
      borderStyle: "solid",
      borderStartStartRadius: "8px",
      borderStartEndRadius: "8px",
      borderEndStartRadius: "8px",
      borderEndEndRadius: "8px",
      cursor: "pointer",
      transition: "background-color 120ms ease, border-color 120ms ease, color 120ms ease",
    },
    variants: {
      variant: {
        ghost: {
          backgroundColor: "transparent",
          borderColor: "lineMuted",
          color: "fgMuted",
          _hover: {
            backgroundColor: "cardElevated",
            color: "fg",
          },
        },
        secondary: {
          backgroundColor: "cardElevated",
          borderColor: "line",
          color: "fgMuted",
          _hover: {
            color: "fg",
            backgroundColor: "surfacePressed",
          },
        },
        danger: {
          backgroundColor: "dangerSoft",
          borderColor: "dangerSoft",
          color: "danger",
          _hover: {
            borderColor: "danger",
          },
        },
      },
    },
    defaultVariants: {
      variant: "secondary",
    },
  }),
  icon: css({
    inlineSize: "18px",
    blockSize: "18px",
    flexShrink: "0",
  }),
  feedback: css({
    marginBlockStart: "18px",
    marginBlockEnd: "0",
    marginInline: "0",
    paddingBlock: "12px",
    paddingInline: "14px",
    color: "warning",
    backgroundColor: "orangeSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "orange",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "14px",
    fontWeight: "700",
  }),
  formPanel: css({
    display: "grid",
    gap: "14px",
  }),
  formHeader: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  }),
  formTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "20px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  field: css({
    display: "grid",
    gap: "7px",
  }),
  label: css({
    color: "fgMuted",
    fontSize: "13px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  input: css({
    inlineSize: "100%",
    minBlockSize: "46px",
    boxSizing: "border-box",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  textarea: css({
    inlineSize: "100%",
    minBlockSize: "96px",
    resize: "block",
    boxSizing: "border-box",
    paddingBlock: "11px",
    paddingInline: "12px",
    backgroundColor: "bgSoft",
    color: "fg",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "16px",
    lineHeight: "1.4",
    outline: "none",
    _focus: {
      borderColor: "accent",
      boxShadow: "0 0 0 3px token(colors.accentSoft)",
    },
    _placeholder: {
      color: "fgSubtle",
    },
  }),
  formActions: css({
    display: { base: "grid", sm: "flex" },
    gridTemplateColumns: "1fr",
    flexWrap: "wrap",
    gap: "10px",
  }),
  emptyState: css({
    display: "grid",
    justifyItems: "start",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
    paddingBlock: { base: "20px", sm: "24px" },
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  emptyIcon: css({
    inlineSize: "32px",
    blockSize: "32px",
    color: "accent",
  }),
  emptyTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "22px",
    fontWeight: "800",
    lineHeight: "1.1",
  }),
  emptyDescription: css({
    maxInlineSize: "520px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "15px",
    lineHeight: "1.45",
  }),
  exerciseList: css({
    display: "grid",
    gap: "12px",
    marginBlockStart: { base: "18px", sm: "24px" },
    marginBlockEnd: "0",
    marginInline: "0",
    paddingInlineStart: "0",
    listStyle: "none",
  }),
  exerciseCard: css({
    display: "grid",
    gap: { base: "12px", sm: "14px" },
    gridTemplateColumns: {
      base: "minmax(0, 1fr) auto",
      sm: "minmax(0, 1fr) auto",
    },
    paddingBlock: { base: "14px", sm: "16px" },
    paddingInline: "16px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "lineMuted",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
  }),
  exerciseContent: css({
    minInlineSize: "0",
    display: "grid",
    gap: "10px",
  }),
  exerciseHeading: css({
    display: "grid",
    gap: "4px",
  }),
  exerciseName: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fg",
    fontSize: "19px",
    fontWeight: "800",
    lineHeight: "1.15",
  }),
  equipment: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgSubtle",
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.2",
  }),
  muscleGroups: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  }),
  muscleGroup: css({
    paddingBlock: "5px",
    paddingInline: "8px",
    color: "accent",
    backgroundColor: "accentSoft",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "accentSoft",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    fontSize: "12px",
    fontWeight: "800",
    lineHeight: "1",
  }),
  muscleGroupMuted: css({
    color: "fgSubtle",
    fontSize: "13px",
    fontWeight: "700",
  }),
  notes: css({
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  cardActions: css({
    display: "flex",
    gap: "8px",
    alignItems: "start",
    justifyContent: {
      base: "end",
      sm: "end",
    },
  }),
  dialogOverlay: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "30",
    backgroundColor: "rgba(13, 17, 23, 0.78)",
    backdropFilter: "blur(8px)",
  }),
  dialogViewport: css({
    position: "fixed",
    insetBlock: "0",
    insetInline: "0",
    zIndex: "31",
    display: "grid",
    placeItems: "center",
    paddingBlock: "16px",
    paddingInline: "16px",
    pointerEvents: "none",
  }),
  formDialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "520px",
    maxBlockSize: "calc(100vb - 32px)",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "card",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  dialogContent: css({
    inlineSize: "100%",
    maxInlineSize: "420px",
    maxBlockSize: "calc(100vb - 32px)",
    display: "grid",
    gap: "14px",
    overflowBlock: "auto",
    paddingBlock: "18px",
    paddingInline: "18px",
    backgroundColor: "cardElevated",
    borderBlockWidth: "1px",
    borderInlineWidth: "1px",
    borderStyle: "solid",
    borderColor: "line",
    borderStartStartRadius: "8px",
    borderStartEndRadius: "8px",
    borderEndStartRadius: "8px",
    borderEndEndRadius: "8px",
    boxShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    pointerEvents: "auto",
  }),
  dialogTitle: css({
    marginBlock: "0",
    marginInline: "0",
    color: "danger",
    fontSize: "20px",
    fontWeight: "900",
    lineHeight: "1.2",
  }),
  dialogDescription: css({
    display: "grid",
    gap: "4px",
    marginBlock: "0",
    marginInline: "0",
    color: "fgMuted",
    fontSize: "14px",
    lineHeight: "1.45",
  }),
  dialogActions: css({
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "end",
    gap: "8px",
  }),
  visuallyHidden: css({
    srOnly: true,
  }),
};
